Various improvements
Acedev003/hexdump pull request #1
Opened 2022-06-03 23:36 UTC by devenblake

## style
I tried to use the style you're already using. I unindented some lines that your editor probably auto-indented because of the preceding fprintfs.

## ctype.h
isprint(3) provides the `c >= ' ' && c <= '~'` functionality you were expecting.

## print_sidebar
This does away with a lot of repeated code.

## stdbool.h
This is a C99 thing but you're already using some C99 additions (I see variable declarations in `for` statements) so I don't think this is a problem.

These are some improvements. Consider doing away with hard-coded line[0],line[1]...s and use a `for` loop that checks for `i < BYTES_PER_LINE` when printing the bytes. I also see some type warnings with fprintf(3) formatting that could be fixed. All in all, pretty cool hexdump(1) implementation!

2022-06-04 14:16 UTC, Acedev003 requested changes
Hi devenblake 👋
Thanks for your contribution.
Building your commit, I got an error in the main.c function at lines 15 and 68 due to the change in the hexdump.h header. Could you fix the same and put in a new PR.

2022-06-04 22:24 UTC, devenblake commented
I instead put an implementation of stdbool.h within the code, which will make it more portable than the non-standard TRUE and FALSE macros you're suggesting.

2022-06-04 22:25 UTC, devenblake reviewed
These changes are uncommon and would make it confusing for developers from modern, standard environments.

2022-06-04 22:31 UTC, devenblake commented
`_Bool` is a built-in type (which probably doesn't exist on legacy compilers) so I just changed it to define the true and false macros in stdbool.h if stdbool.h hasn't been included.

2022-06-05 05:33 UTC, merged

2022-06-05 05:41 UTC, Acedev003 commented
I think the issue was due to a missing stdbool header in the main.c function. Anyways i'll get rid of these confusing TRUE/FALSE defines and replace them with `_Bool ` when I refactor the entire code to address other issues. Thanks for helping me out and pointing out these problems